# Generated by Django 4.0.1 on 2024-03-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
