# Generated by Django 4.0.1 on 2024-03-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_message_file_name_alter_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
